{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kube-escalate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-escalate.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-escalate.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
